### ISSUE TITLE
Inference with HoVer-net: "Out of bounds cropping not allowed, but offset was below 0"

### ISSUE THREAD

**Issue by naguileraleal** [AICAN-Research/FAST-Pathology#67]
Hello again!

I'm trying to use another pre-trained model, HoVer-net, to infer over a WSI using FastPathology. Originally this model is implemented in Pytorch. I converted it to onnx format in order to load it on FastPathology. The conversion was successful.

In order to use the model I implemented the following FastPathology text pipeline
```
PipelineName "HoVer-net nuclei segmentation and classification"
PipelineDescription "HoVer-Net"
PipelineInputData WSI "Whole-slide image"
PipelineOutputData Segmentation stitcher 0
Attribute classes "nolabe;neopla;inflam;connec;necros;no-neo"

### Processing chain

ProcessObject tissueSeg TissueSegmentation
Input 0 WSI

ProcessObject patch PatchGenerator
Attribute patch-size 256 256
Attribute patch-level 1
Attribute patch-overlap 0.1
Input 0 WSI
Input 1 tissueSeg 0

ProcessObject batch ImageToBatchGenerator
Attribute max-batch-size 1
Input 0 patch 0

ProcessObject network NeuralNetwork
Attribute scale-factor 0.003921568627451
Attribute model "/home/sofia/Documents/FING/Proyecto/hover_net/hovernet_pannuke.onnx"
Attribute dimension-ordering "channel-first"
Input 0 batch 0

ProcessObject converter TensorToSegmentation
Input 0 network 0

ProcessObject stitcher PatchStitcher
Input 0 converter 0

### Renderers
Renderer imgRenderer ImagePyramidRenderer
Input 0 WSI

Renderer segRenderer SegmentationRenderer
Attribute border-opacity 0.5
Input 0 stitcher 0
```

I'm now stuck with this error trying to process the image
![image](https://user-images.githubusercontent.com/52642950/231028256-5bdc896f-157a-4f12-a727-86bc71fd6949.png)

So, in an attempt to debug the pipeline, I wrote an analogous pipeline using the FAST Python module

```
import fast

WSIPath = "./44-D5.svs"
patchSize = 256

# https://github.com/vqdang/hover_net#usage-and-options-1
#'fast' model mode uses a 256x256 patch input and 164x164 patch output.

level = 0
magnification = 40

# The PanNuke Dataset: "We re-sized the selected visual fields so that all images were at 40× resolution"
# In this link info about level magnification can be found: https://fast.eriksmistad.no/python-tutorial-wsi.html 
# Level 0 in the pyramid is the full resolution image W x H, while the next level 1 is the same image but with a reduced size, 
# typically half the width and height of the previous level (W/2 x H/2).

importer = fast.WholeSlideImageImporter\
    .create(WSIPath)

imageRenderer = fast.ImageRenderer.create().connect(importer)

tissueSegmentation = fast.TissueSegmentation.create().connect(importer)

patchGenerator = fast.PatchGenerator.create(patchSize, patchSize, magnification=magnification, overlapPercent=0.1)\
    .connect(0, importer)\
    .connect(1, tissueSegmentation)

print("Patch generator created")

### Batch patches ###
maxBatchSize = 1
batchGenerator = fast.ImageToBatchGenerator.create(maxBatchSize=maxBatchSize).connect(0, patchGenerator)

### Create neural network object ###
modelPath = "./hovernet_pannuke.onnx"
nn = fast.NeuralNetwork.create(
    scaleFactor=0.003921568627451,
    modelFilename=modelPath,
    # dimensionOrdering='channel-first'
    ).connect(0, batchGenerator)

print("Neural network created")

### Convert output to segmentation ###
converter = fast.TensorToSegmentation.create().connect(0, nn)

print("Converter created")

### Create patch stitcher to generate pyramidal tiff output ###
stitcher = fast.PatchStitcher.create(patchesAreCropped=True).connect(0, converter)

print("Stitcher created")

### Create renderers to show both original WSI and segmentation output ###
wsiRenderer = fast.ImagePyramidRenderer.create().connect(0, importer)
segmentationRenderer = fast.SegmentationRenderer.create(borderOpacity=0.5, colors={1: fast.Color.Black(), 2: fast.Color.Red(), 3: fast.Color.Green(), 4: fast.Color.Blue(), 5: fast.Color.Yellow(), 6: fast.Color.White()},).connect(stitcher)

### Create window to display segmentation###   
fast.SimpleWindow2D.create()\
    .connect(wsiRenderer)\
    .connect(segmentationRenderer)\
    .run()
```

Unfortunately this script crashes with the same exception
```
(env) python ./hovernet-pipeline.py

     - Powered by -
   _______   __________
  / __/ _ | / __/_  __/   https://fast.eriksmistad.no
 / _// __ |_\ \  / /               v4.6.0
/_/ /_/ |_/___/ /_/

Patch generator created
WARNING [18176] Failed to load plugin because The specified module could not be found.

Neural network created
Converter created
Stitcher created
WARNING [5340] Patch size must be a multiple of 16 (TIFF limitation). Adding some overlap (32, 32) to fix.
ERROR [18176] FAST exception caught in Qt event handler Out of bounds cropping not allowed, but offset was below 0.
Traceback (most recent call last):
  File "c:\Users\nicol\Documents\FING\proyecto\fastpathology\hovernet-pipeline.py", line 63, in <module>
    fast.SimpleWindow2D.create()\
  File "C:\Users\nicol\Documents\FING\proyecto\env\lib\site-packages\fast\fast.py", line 15006, in run
    return _fast.Window_run(self)
RuntimeError: Out of bounds cropping not allowed, but offset was below 0.
```

I've tried this process on both Windows 11 and Ubuntu 20.04, using FastPathology v1.1.0, FAST v4.6.0, python v3.9.0.

As always, any help is much appreciated!

**Comment by smistad** [comment]
There is a HoVerNet implementation in the data hub. Menu -> Download models & pipelines -> Nuclei Classification (PanNuke, 20X, PanNuke).

If you still want to use your own model, here is how that pipeline file looks like, which you can adapt to your model:

Some of the key differences are:
* "Attribute patches-are-cropped true" on the PatchStitcher. This is needed because this network performs cropping of the input patches.
* "Attribute ignore-channels 6 7 8" on SegmentationNetwork. This essentially ignores the horizontal and vertical position encodings and the nuclei binary segmentation.
* The patch-overlap on PatchGenerator must be correct: Attribute patch-overlap 0.1796875

```
PipelineName "Nuclei Classification (20X, PanNuke, HoVerNet)"
PipelineDescription "This pipeline segments cell nuclei into one of 5 different classes: Neoplastic, Inflammatory, Connective, Dead, Non-Neoplastic Epithelial. It is trained on the PanNuke dataset using the HoVerNet architecture.
The model used is part of the publication 'A Pragmatic Machine Learning Approach to Quantify Tumor-Infiltrating Lymphocytes in Whole Slide Images' Cancers 2022.
PipelineInputData WSI "Whole-slide image"
PipelineOutputData Segmentation stitcher 0
Attribute classes "Background;Neoplastic;Inflammatory;Connective;Dead;Non-Neoplastic Epithelial"

### Processing chain

ProcessObject tissueSeg TissueSegmentation
Input 0 WSI

ProcessObject patch PatchGenerator
Attribute patch-size 256 256
Attribute patch-magnification 20
Attribute patch-overlap 0.1796875
Input 0 WSI
Input 1 tissueSeg 0

ProcessObject network SegmentationNetwork
#Attribute scale-factor 0.003921568627451
Attribute model "$CURRENT_PATH$/../nuclei-classification-model-hovernet-pannuke/pannuke_aug-p-linear_2-1.0.onnx"
Attribute ignore-channels 6 7 8
Input 0 patch 0

ProcessObject stitcher PatchStitcher
Attribute patches-are-cropped true
Input 0 network 0

### Renderers
Renderer imgRenderer ImagePyramidRenderer
Input 0 WSI

Renderer segRenderer SegmentationRenderer
Attribute border-opacity 0.5
Input 0 stitcher 0
```

**Comment by naguileraleal** [comment]
Thank you for your quick response!

I didn't notice that the HoVerNet model was already available at the model hub; embarrassing...
I tested your pipeline with my version of the model and it worked fine.

Thanks again. I'm closing this issue now.
